// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogoekxzobhthfjecypxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nb2VreHpvYmh0aGZqZWN5cHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjY2NTMsImV4cCI6MjA1OTcwMjY1M30.RUZsVCPyzZIGY5Cn8K4XVMOemY_WUwzB16G8PDsJrqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);